### ISSUE TITLE
Uncaught TypeError by MailPoet LogHandler.php

### ISSUE THREAD

**Issue by simison** [mailpoet/mailpoet#3785]
**Describe the bug**

Site https://simisontestingfseatomic1.wpcomstaging.com/

Everything seems to work in wp-admin and on the frontend, but I received this email from My WordPress.com Atomic site:

> Howdy!
> 
> Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.
> 
> In this case, WordPress caught an error with one of your plugins, MailPoet 3 (New).
> 
> First, visit your website (https://simisontestingfseatomic1.wpcomstaging.com/) and check for any visible issues. Next, visit the page where the error was caught (https://simisontestingfseatomic1.wpcomstaging.com/wp-cron.php?doing_wp_cron=1636104143.0234820842742919921875) and check for any visible issues.
> 
> Please contact your host for assistance with investigating this issue further.
> 
> If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.
> 
> https://simisontestingfseatomic1.wpcomstaging.com/wp-login.php?action=enter_recovery_mode&rm_token=zy8dTZkq0kr45B7Kyj2cCH&rm_key=oZvALHfgFMYSVZ4MBrykHJ
> 
> To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.
> 
> When seeking help with this issue, you may be asked for some of the following information:
> WordPress version 5.8.1
> Current theme: Maywood (version 1.5.12)
> Current plugin: MailPoet 3 (New) (version 3.73.1)
> PHP version 7.3.31
> 
> 
> 
> Error Details
> =============
> An error of type E_ERROR was caused in line 37 of the file /srv/htdocs/wp-content/plugins/mailpoet/lib/Logging/LogHandler.php. Error message: Uncaught TypeError: Argument 2 passed to MailPoet\Logging\LogHandler::__construct() must be an instance of MailPoetVendor\Doctrine\ORM\EntityManager, int given, called in /srv/htdocs/wp-content/plugins/mailpoet/lib/Logging/LoggerFactory.php on line 74 and defined in /srv/htdocs/wp-content/plugins/mailpoet/lib/Logging/LogHandler.php:37
> Stack trace:
> #0 /srv/htdocs/wp-content/plugins/mailpoet/lib/Logging/LoggerFactory.php(74): MailPoet\Logging\LogHandler->__construct(Object(MailPoet\Logging\LogRepository), 400)
> #1 /srv/htdocs/wp-content/plugins/mailpoet/lib/Newsletter/Scheduler/PostNotificationScheduler.php(60): MailPoet\Logging\LoggerFactory->getLogger('post-notificati...')
> #2 /wordpress/core/5.8.1/wp-includes/class-wp-hook.php(303): MailPoet\Newsletter\Scheduler\PostNotificationScheduler->transitionHook('draft', 'new', Object(WP_Post))
> #3 /wordpress/core/5.8.1/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
> #4 /wordpress/core/5.8.1/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
> #5 /wordpress/core/5.8.1/wp-includes/post.php(5098): do_action('transition_post...', 'draft', 'new', Object(WP_Post))
> #6 /wordpress/core/5.8.1/wp-includes/post.php(4368): wp_transition_post_status('draft', 'new', Object(WP_Post))
> #7 /wordpress/plugins/jetpack/10.4-a.1/modules/sitemaps/sitemap-librarian.php(94): wp_insert_post(Array)
> #8 /wordpress/plugins/jetpack/10.4-a.1/modules/sitemaps/sitemap-builder.php(714): Jetpack_Sitemap_Librarian->store_sitemap_data(1, 'jp_sitemap', '

**To reproduce**
I have not set up MailPoet but I have it installed and activated.

The site has WooCommerce and Jetpack plugins installed and active.

My site has the latest Gutenberg and FSE active. 

**Actual behavior**
—
**Expected behavior**
—
**Screenshots**
—
**Versions (please complete the following information):**
- WordPress version: 5.8.1
- PHP version: N/A
- MailPoet version: 3.73.1

**Additional context**

**Comment by brezocordero** [comment]
Hi @simison 
Thank you for the report.

We have made a few changes in the LogHandler recently that have caused similar issues.
We have a PR coming that will be released soon and should fix those issues:
https://github.com/mailpoet/mailpoet/pull/3733

We will update here after the release to check if the error is not happening any more on your end.

**Comment by simison** [comment]
I'm not sure how to test since all I got was an email, and couldn't see issues at the WP admin.

Thanks for the quick fix!
